# Generated by Django 2.0.5 on 2019-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20190614_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
