# Generated by Django 2.0.5 on 2019-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='manufacturer',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
