# Generated by Django 2.1.1 on 2019-06-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Scope', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='topic',
            field=models.CharField(max_length=128, verbose_name='Категория'),
        ),
    ]
