# Generated by Django 2.0.5 on 2019-06-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190620_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='category',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='main',
            field=models.BooleanField(verbose_name='Основная'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='scope',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.Scope', verbose_name='Категории'),
        ),
    ]
