# Generated by Django 2.0.5 on 2019-06-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190620_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Scope', verbose_name='Категории'),
        ),
    ]
