# Generated by Django 2.0.5 on 2019-06-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190620_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='main',
            new_name='is_main',
        ),
    ]
