# Generated by Django 2.0.5 on 2019-06-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190620_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='ArticleScope',
        ),
    ]
