# Generated by Django 2.0.5 on 2019-06-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_scope_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': 'Тематика статьи',
                'verbose_name_plural': 'Тематика статьи',
            },
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='scope',
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Разделы', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='topic',
            field=models.CharField(max_length=30, verbose_name='Раздел'),
        ),
        migrations.DeleteModel(
            name='ArticleScope',
        ),
        migrations.AddField(
            model_name='aboutscope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Scope'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_scopes',
            field=models.ManyToManyField(through='articles.AboutScope', to='articles.Scope'),
        ),
    ]
